apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web
    image: azorinmsu1/otus:latest
  initContainers:
  - name: web-init
    image: busybox:latest
    command: ['sh', '-c', 'wget -0- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app    
  volumes:
  - name: app
    emptyDir: {}
